### ISSUE TITLE
Can't use the package after installing it

### ISSUE THREAD

**Issue by Calinou** [Lorti/resemble-image#1]
I'm working on a command-line interface for this module, but I can't use it in Node.js 12.6.0:

```
internal/modules/cjs/loader.js:236
      throw err;
      ^

Error: Cannot find module '/home/hugo/Documents/Git/Calinou/resemble-image-cli/node_modules/resemble-image/dist/main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:228:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:365:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:612:27)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/hugo/Documents/Git/Calinou/resemble-image-cli/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/hugo/Documents/Git/Calinou/resemble-image-cli/node_modules/resemble-image/package.json',
  requestPath: 'resemble-image'
}
```

This is the script I have so far:

```javascript
const getEqualWidthStops = require('resemble-image').getEqualWidthStops
const getVariableWidthStops = require('resemble-image').getVariableWidthStops

const imagePath = '/some/path.jpg'

getEqualWidthStops(imagePath, { fidelity: 4 }).then((stops) => console.log(stops))
getVariableWidthStops(imagePath, { fidelity: 4 }).then((stops) => console.log(stops))
```

It seems compiled files are expected to be present in the `dist/` directory, but that directory isn't present in the installed package. This is the full directory structure I have locally:

```
❯ tree -a node_modules/resemble-image
node_modules/resemble-image
├── .editorconfig
├── .idea
│   ├── copyright
│   │   └── profiles_settings.xml
│   ├── encodings.xml
│   ├── inspectionProfiles
│   │   ├── profiles_settings.xml
│   │   └── Project_Default.xml
│   ├── jsLibraryMappings.xml
│   ├── misc.xml
│   ├── modules.xml
│   ├── postcss-resemble-image.iml
│   ├── vcs.xml
│   ├── watcherTasks.xml
│   └── workspace.xml
├── LICENSE
├── .npmignore
├── package.json
├── README.md
├── src
│   ├── main.js
│   └── __tests__
│       ├── main.js
│       └── waves.jpg
└── .travis.yml
```

PS: Thanks for creating this library :slightly_smiling_face:

**Comment by Lorti** [comment]
This package is 3 years old and new versions of npm don’t run the `prepublish` script on install, which is why `dist/main` is missing. I will publish a new version, so that the file gets generated.
Can you please try if resemble-image@1.0.2 fixes your problem?

**Comment by Calinou** [comment]
@Lorti It works, thanks! :heart:

I published the CLI at https://www.npmjs.com/package/resemble-image-cli :smiley:
